//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 06:06:34 PM IST 
//


package com.wellsfargo.service.provider.trust.bis.entity.assetsetup._2015;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wellsfargo.service.provider.trust.bis.entity.assetsetup._2015 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AssetSetupsAssetSetupIndustryMarketableCusipTicker_QNAME = new QName("http://service.wellsfargo.com/provider/trust/bis/entity/assetSetup/2015/", "IndustryMarketableCusipTicker");
    private final static QName _AssetSetupsAssetSetupNonIndustryCusips_QNAME = new QName("http://service.wellsfargo.com/provider/trust/bis/entity/assetSetup/2015/", "NonIndustryCusips");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wellsfargo.service.provider.trust.bis.entity.assetsetup._2015
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AssetSetups }
     * 
     */
    public AssetSetups createAssetSetups() {
        return new AssetSetups();
    }

    /**
     * Create an instance of {@link AssetSetups.AssetSetup }
     * 
     */
    public AssetSetups.AssetSetup createAssetSetupsAssetSetup() {
        return new AssetSetups.AssetSetup();
    }

    /**
     * Create an instance of {@link AssetSetups.AssetSetup.Bond }
     * 
     */
    public AssetSetups.AssetSetup.Bond createAssetSetupsAssetSetupBond() {
        return new AssetSetups.AssetSetup.Bond();
    }

    /**
     * Create an instance of {@link AssetSetups.AssetSetup.CommercialPaperDiscount }
     * 
     */
    public AssetSetups.AssetSetup.CommercialPaperDiscount createAssetSetupsAssetSetupCommercialPaperDiscount() {
        return new AssetSetups.AssetSetup.CommercialPaperDiscount();
    }

    /**
     * Create an instance of {@link AssetSetups.AssetSetup.Equity }
     * 
     */
    public AssetSetups.AssetSetup.Equity createAssetSetupsAssetSetupEquity() {
        return new AssetSetups.AssetSetup.Equity();
    }

    /**
     * Create an instance of {@link AssetSetups.AssetSetup.GICGAC }
     * 
     */
    public AssetSetups.AssetSetup.GICGAC createAssetSetupsAssetSetupGICGAC() {
        return new AssetSetups.AssetSetup.GICGAC();
    }

    /**
     * Create an instance of {@link AssetSetups.AssetSetup.InsuranceAnnuityPolicy }
     * 
     */
    public AssetSetups.AssetSetup.InsuranceAnnuityPolicy createAssetSetupsAssetSetupInsuranceAnnuityPolicy() {
        return new AssetSetups.AssetSetup.InsuranceAnnuityPolicy();
    }

    /**
     * Create an instance of {@link AssetSetups.AssetSetup.Liability }
     * 
     */
    public AssetSetups.AssetSetup.Liability createAssetSetupsAssetSetupLiability() {
        return new AssetSetups.AssetSetup.Liability();
    }

    /**
     * Create an instance of {@link AssetSetups.AssetSetup.Miscellaneous }
     * 
     */
    public AssetSetups.AssetSetup.Miscellaneous createAssetSetupsAssetSetupMiscellaneous() {
        return new AssetSetups.AssetSetup.Miscellaneous();
    }

    /**
     * Create an instance of {@link AssetSetups.AssetSetup.NonMarketableCertificateOfDepositSavingsAccount }
     * 
     */
    public AssetSetups.AssetSetup.NonMarketableCertificateOfDepositSavingsAccount createAssetSetupsAssetSetupNonMarketableCertificateOfDepositSavingsAccount() {
        return new AssetSetups.AssetSetup.NonMarketableCertificateOfDepositSavingsAccount();
    }

    /**
     * Create an instance of {@link AssetSetups.AssetSetup.Fund }
     * 
     */
    public AssetSetups.AssetSetup.Fund createAssetSetupsAssetSetupFund() {
        return new AssetSetups.AssetSetup.Fund();
    }

    /**
     * Create an instance of {@link AssetSetups.AssetSetup.NTCusips }
     * 
     */
    public AssetSetups.AssetSetup.NTCusips createAssetSetupsAssetSetupNTCusips() {
        return new AssetSetups.AssetSetup.NTCusips();
    }

    /**
     * Create an instance of {@link AssetSetups.AssetSetup.RealEstate }
     * 
     */
    public AssetSetups.AssetSetup.RealEstate createAssetSetupsAssetSetupRealEstate() {
        return new AssetSetups.AssetSetup.RealEstate();
    }

    /**
     * Create an instance of {@link AssetSetups.AssetSetup.Repo }
     * 
     */
    public AssetSetups.AssetSetup.Repo createAssetSetupsAssetSetupRepo() {
        return new AssetSetups.AssetSetup.Repo();
    }

    /**
     * Create an instance of {@link AssetSetups.AssetSetup.SLUG }
     * 
     */
    public AssetSetups.AssetSetup.SLUG createAssetSetupsAssetSetupSLUG() {
        return new AssetSetups.AssetSetup.SLUG();
    }

    /**
     * Create an instance of {@link AssetSetups.AssetSetup.TimeDeposit }
     * 
     */
    public AssetSetups.AssetSetup.TimeDeposit createAssetSetupsAssetSetupTimeDeposit() {
        return new AssetSetups.AssetSetup.TimeDeposit();
    }

    /**
     * Create an instance of {@link AssetSetups.AssetSetup.UnitizedCUSIP }
     * 
     */
    public AssetSetups.AssetSetup.UnitizedCUSIP createAssetSetupsAssetSetupUnitizedCUSIP() {
        return new AssetSetups.AssetSetup.UnitizedCUSIP();
    }

    /**
     * Create an instance of {@link AssetSetups.AssetSetup.SecurityInformation }
     * 
     */
    public AssetSetups.AssetSetup.SecurityInformation createAssetSetupsAssetSetupSecurityInformation() {
        return new AssetSetups.AssetSetup.SecurityInformation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.wellsfargo.com/provider/trust/bis/entity/assetSetup/2015/", name = "IndustryMarketableCusipTicker", scope = AssetSetups.AssetSetup.class)
    public JAXBElement<String> createAssetSetupsAssetSetupIndustryMarketableCusipTicker(String value) {
        return new JAXBElement<String>(_AssetSetupsAssetSetupIndustryMarketableCusipTicker_QNAME, String.class, AssetSetups.AssetSetup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://service.wellsfargo.com/provider/trust/bis/entity/assetSetup/2015/", name = "NonIndustryCusips", scope = AssetSetups.AssetSetup.class)
    public JAXBElement<String> createAssetSetupsAssetSetupNonIndustryCusips(String value) {
        return new JAXBElement<String>(_AssetSetupsAssetSetupNonIndustryCusips_QNAME, String.class, AssetSetups.AssetSetup.class, value);
    }

}
