//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 06:06:34 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://service.wellsfargo.com/provider/trust/bis/entity/assetSetup/2015/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.wellsfargo.service.provider.trust.bis.entity.assetsetup._2015;
