//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 05:19:57 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.example.com/a", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
xmlns={@XmlNs(prefix="parse", namespaceURI="http://www.w3.org/2001/XMLSchema"), @XmlNs(prefix="xsi", namespaceURI="http://www.w3.org/2001/XMLSchema/test")})
package com.example.a;

import javax.xml.bind.annotation.XmlNs;
